about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group'),
    path('new/', views.new_post, name='new_post'),
    path("follow/", views.follow_index, name="follow_index"),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/<int:post_id>/', views.post_view,
         name='post_view'),
    path('<str:username>/<int:post_id>/edit/', views.post_edit,
         name='post_edit'),
    path('<str:username>/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path("<str:username>/follow/", views.profile_follow,
         name="profile_follow"),
    path("<str:username>/unfollow/", views.profile_unfollow,
         name="profile_unfollow"),
]

yatube/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500  # noqa
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

handler404 = "posts.views.page_not_found"  # noqa
handler500 = "posts.views.server_error"  # noqa

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("posts.urls")),
    path('about/', include('about.urls', namespace='about')),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

templates/includes/comments.html
<!-- Форма добавления комментария -->
{% load user_filters %}

{% if user.is_authenticated %}
<div class="card my-4">
    <form method="post" action="{% url 'posts:add_comment' user post.id %}">
        {% csrf_token %}
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
            <div class="form-group">
                    {{ form.text|addclass:'form-control' }}
                    {#{{ form.text }}#}
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
        </div>
    </form>
</div>
{% endif %}

<!-- Комментарии -->
{% for item in comments %}
<div class="media card mb-4">
    <div class="media-body card-body">
        <h5 class="mt-0">
            <a href="{% url 'posts:profile' item.author.username %}"
               name="comment_{{ item.id }}">
                {{ item.author.username }}
            </a>
        </h5>
        <p>{{ item.created }}</p>
        <p>{{ item.text | linebreaksbr }}</p>
    </div>
</div>
{% endfor %}

templates/includes/footer.html
<footer class="pt-4 my-md-5 pt-md-5 border-top" >
    <p class="m-0 text-dark text-center ">
        <a href="{% url 'about:author' %}">Об авторе</a>
        <a href="{% url 'about:tech' %}">Технологии</a>
  </p>
    <p class="m-0 text-dark text-center">Социальная сеть <span style="color:red">Ya</span>tube © {% now 'Y' %}, все права защищены.</p>
</footer>

templates/includes/menu.html
{% if user.is_authenticated %} 
<div class="row">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a class="nav-link {% if index %}active{% endif %}" href="{% url 'posts:index' %}">
                  Все авторы
            </a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% if follow %}active{% endif %}" href="{% url 'posts:follow_index' %}">
                Избранные авторы
            </a>
        </li>
    </ul>
</div>
{% endif %}

templates/includes/nav.html
<nav class="navbar navbar-light" style="background-color: #999999;">
    <a class="navbar-brand" href="{% url 'posts:index' %}"><span style="color:red">Ya</span>tube</a>
    <nav class="my-2 my-md-0 mr-md-3">
        {% if user.is_authenticated %}
        Пользователь: {{ user.username }}.
        <a class="p-2 text-dark" href="{% url 'password_change' %}">Изменить пароль</a>
        <a class="p-2 text-dark" href="{% url 'logout' %}">Выйти</a>
        <a class="p-2 text-dark" href="{% url 'posts:new_post' %}">Новая запись</a>
        {% else %}
        <a class="p-2 text-dark" href="{% url 'login' %}">Войти</a> |
        <a class="p-2 text-dark" href="{% url 'signup' %}">Регистрация</a>
        {% endif %}
    </nav>
</nav>

templates/includes/post_card.html
<div class="card mb-3 mt-1 shadow-sm">
    {% load thumbnail %}
    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
    <img class="card-img" src="{{ im.url }}">
    {% endthumbnail %}

    <div class="card-body">
        <p class="card-text">
            <!-- Ссылка на страницу автора в атрибуте href; username автора в тексте ссылки -->
            <a name='post_{{ post.id }}' href={% url 'posts:profile' post.author.username %}><strong class="d-block text-gray-dark">{{ post.author.get_full_name }}</strong></a>
                <strong class="d-block text-gray-dark">@{{ post.author }}</strong>

            <!-- Текст поста -->
            <p>{{ post.text|linebreaksbr }}</p>

            <!-- Если пост относится к какому-нибудь сообществу, то отобразим ссылку на него через # -->
            {% if post.group %}
                <a class="card-link muted" href="{% url 'posts:group' post.group.slug %}">
                <strong class="d-block text-gray-dark">#{{ post.group.title }}</strong>
                </a>
            {% endif %}
        </p>
        <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group ">

                {% if post.comments.exists %}
                <div>
                    Комментариев: {{ post.comments.count }}
                </div>
                {% endif %}
                <a class="btn btn-sm btn-primary" href="{% url 'posts:post_view' post.author.username post.id %}" role="button">Добавить комментарий</a>

                <!-- Ссылка на редактирование, показывается только автору записи -->
                {% if user.username == post.author.username %}
                    <a class="btn btn-sm text-muted"
                       href={% url "posts:post_edit" post.author.username post.id %}
                       role="button">Редактировать</a>
                {% endif %}
            </div>
            <!-- Дата публикации  -->
            <small class="text-muted">{{ post.pub_date|date:"d M Y" }} Post ID {{ post.id }} </small>
        </div>
    </div>
</div>

templates/includes/user_card.html
<div class="card">
    <div class="card-body">
        <div class="h2">
            <!-- Имя автора -->
            {{ author.get_full_name }}
        </div>
        <div class="h3 text-muted">
            <!-- username автора -->
            {{ author }}
        </div>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
            <div class="h6 text-muted">
                Подписчиков: {{ author_follows }} <br />
                Подписан на: {{ user_follows }}
            </div>
        </li>
        <li class="list-group-item">
            <div class="h6 text-muted">
                <!--Количество записей -->
                Записей: {{ posts_amount }}
            </div>
        </li>
    </ul>
</div>