about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group'),
    path('new/', views.new_post, name='new_post'),
    path("follow/", views.follow_index, name="follow_index"),
    path('<str:username>/', views.profile, name='profile'),
    path('<str:username>/<int:post_id>/', views.post_view,
         name='post_view'),
    path('<str:username>/<int:post_id>/edit/', views.post_edit,
         name='post_edit'),
    path('<str:username>/<int:post_id>/comment/', views.add_comment,
         name='add_comment'),
    path("<str:username>/follow/", views.profile_follow,
         name="profile_follow"),
    path("<str:username>/unfollow/", views.profile_unfollow,
         name="profile_unfollow"),
]

yatube/urls.py
from django.conf import settings
from django.conf.urls import handler404, handler500  # noqa
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

handler404 = "posts.views.page_not_found"  # noqa
handler500 = "posts.views.server_error"  # noqa

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("posts.urls")),
    path('about/', include('about.urls', namespace='about')),
    path("auth/", include("users.urls")),
    path("auth/", include("django.contrib.auth.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

    import debug_toolbar

    urlpatterns += (path("__debug__/", include(debug_toolbar.urls)),)

posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        'Заголовок',
        max_length=200,
        help_text='Дайте короткое название группе',
    )
    slug = models.SlugField(
        'Слаг',
        max_length=20,
        unique=True,
        help_text=('Укажите адрес для страницы группы. Используйте только '
                   'латиницу, цифры, дефисы и знаки подчёркивания'),
    )
    description = models.TextField(
        'Описание',
        help_text='Опишите группу',
    )

    def __str__(self):
        return f'{self.title}'


class Post(models.Model):
    text = models.TextField(
        'Текст',
        help_text='Опишите новость',
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.CASCADE,
        related_name='posts',
    )
    group = models.ForeignKey(
        Group,
        verbose_name='Группа',
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        help_text='Выберите группу'
    )
    image = models.ImageField(upload_to='posts/', blank=True, null=True)

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        verbose_name='Комментарий к посту',
        on_delete=models.CASCADE,
        related_name='comments_post',
        null=True,
    )
    author = models.ForeignKey(
        User,
        verbose_name='Автор',
        on_delete=models.CASCADE,
        related_name='comments',
    )
    text = models.TextField(
        'Текст',
        help_text='Ваш коментарий',
    )
    created = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )

    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        verbose_name='Подписывающийся',
        on_delete=models.CASCADE,
        related_name='follower',
        null=True,
    )

    author = models.ForeignKey(
        User,
        verbose_name='Автор на которого подписываются',
        on_delete=models.CASCADE,
        related_name='following',
        null=True,
    )

posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['text']
        widgets = {
            'text': forms.Textarea(
                attrs={'cols': 50, 'rows': 10}
            )
        }

posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.http import HttpResponse
from django.shortcuts import redirect
from django.shortcuts import render, get_object_or_404

from yatube.settings import COUNT_POSTS_IN_PAGE
from .forms import PostForm, CommentForm
from .models import Post, Group, User, Comment, Follow


def index(request):
    post_list = Post.objects.all()  # noqa
    paginator = Paginator(post_list, COUNT_POSTS_IN_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'index.html', {'page': page})


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, COUNT_POSTS_IN_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, 'group.html', {'page': page,
                                          'group': group})


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = Post.objects.filter(author__username=username)  # noqa
    posts_amount = post_list.count()
    paginator = Paginator(post_list, COUNT_POSTS_IN_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    # подписано на user'a
    author_follows = Follow.objects.filter(author=author).count()
    # user подписан на
    user_follows = Follow.objects.filter(user=author).count()
    no_author = True
    if request.user == author:
        no_author = False
    following = False
    if request.user.is_authenticated:
        if Follow.objects.filter(user=request.user, author=author).exists():
            following = True
    context = {'author': author,
               'page': page,
               'paginator': paginator,
               'posts_amount': posts_amount,
               'post_list': post_list,
               'author_follows': author_follows,
               'user_follows': user_follows,
               'following': following,
               'no_author': no_author,
               }
    return render(request, 'profile.html', context)


@login_required
def new_post(request):
    form = PostForm(request.POST or None, files=request.FILES or None,)
    if form.is_valid():
        post = form.save(commit=False)
        post.author = request.user
        post.save()
        return redirect('posts:index')
    return render(request, 'new_post.html', {'form': form})


def post_view(request, post_id, username):
    post = get_object_or_404(Post, id=post_id)
    posts_amount = Post.objects.filter(author=post.author).count()  # noqa
    form = CommentForm()
    # подписано на user'a
    author_follows = Follow.objects.filter(author=post.author).count()
    # user подписан на
    user_follows = Follow.objects.filter(user=post.author).count()
    context = {'post': post,
               'author': post.author,
               'posts_amount': posts_amount,
               'comments': Comment.objects.filter(post=post),
               'form': form,
               'author_follows': author_follows,
               'user_follows': user_follows,
               }
    return render(request, 'post.html', context)


@login_required
def post_edit(request, username, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.user != post.author:
        return redirect('posts:profile', username=post.author)
    form = PostForm(request.POST or None,
                    files=request.FILES or None,
                    instance=post)
    if form.is_valid():
        post.save()
        return redirect('posts:post_view',
                        username=post.author,
                        post_id=post_id)
    return render(request, 'new_post.html', {'form': form, 'post': post})


def page_not_found(request, exception):  # noqa
    return render(
        request,
        'misc/404.html',
        {'path': request.path},
        status=404
    )


def server_error(request):
    return render(request, 'misc/500.html', status=500)


@login_required
def add_comment(request, username, post_id):
    user_post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None, instance=None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = user_post
        comment.author = request.user
        comment.save()
        return redirect('posts:post_view',
                        username=user_post.author.username,
                        post_id=user_post.id)
    else:
        return HttpResponse('вы ввели некорректные данные')


@login_required
def follow_index(request):
    user_follow_posts = Post.objects.filter(
        author__following__user=request.user)
    # подписано на user'a
    author_follows = Follow.objects.filter(author=request.user).count()
    # user подписан на
    user_follows = Follow.objects.filter(user=request.user).count()
    paginator = Paginator(user_follow_posts, COUNT_POSTS_IN_PAGE)
    page_number = request.GET.get('page')
    page = paginator.get_page(page_number)
    return render(request, "follow.html", {
        'user_follows': user_follows,
        'author_follows': author_follows,
        'page': page,
    }
    )


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if request.user.username != username:
        Follow.objects.get_or_create(user=request.user, author=author)
    return redirect('posts:profile', username=author)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    Follow.objects.filter(user=request.user, author=author).delete()
    return redirect('posts:profile', username=author)

templates/base.html
<!doctype html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}The Last Social Media You'll Ever Need{% endblock %} | Yatube</title>
    <!-- Загрузка статики -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
    <script src="{% static 'jquery/dist/jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap/dist/js/bootstrap.min.js' %}"></script>
</head>

<body>
    {% include 'includes/nav.html' %}
    <main>
        <div class="container">
            <h1>{% block header %}The Last Social Media You'll Ever Need{% endblock %}</h1>
            {% block content %}
            <!-- Содержимое страницы -->
            {% endblock %}
        </div>
    </main>
    {% include 'includes/footer.html' %}
</body>

</html>

templates/follow.html
{% extends "base.html" %}
{% block title %}Мои подписки{% endblock %}
{% block header %}Мои подписки | {{ user_follows }} на меня подписано {{ author_follows }}{% endblock %}
{% block content %}

    {% load cache %}
    {% cache 20 index_page %}

        {% for post in page %}

            {% include 'includes/post_card.html' %}

        {% endfor %}

    {% endcache %}

    {% include "paginator.html" %}

{% endblock %} 

templates/group.html
{% extends "base.html" %}
{% block title %}Записи сообщества {{ group.title }}{% endblock %}
{% block header %}{{ group.title }}{% endblock %}
{% block content %}
    <p>{{ group.description }}</p>
    {% for post in page %}
        {% include 'includes/post_card.html' %}
    {% endfor %}

    {% include "paginator.html" %}

{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block title %}Последние обновления{% endblock %}
<!--{#{% block header %}Последние обновления{% endblock %}#}-->
{% block content %}
<div class="container">

    {% include 'includes/menu.html' with index=True %}
        <h1>Последние обновления на сайте</h1>


    {% load cache %}
    {% cache 20 index_page %}

        {% for post in page %}
            {% include 'includes/post_card.html' %}
        {% endfor %}

    {% endcache %}

    {% if page.has_other_pages %}
        {% include "paginator.html" with items=page paginator=paginator %}
    {% endif %}

</div>
{% endblock %}

templates/new_post.html
{% extends "base.html" %}
{% block title %}Новый пост{% endblock %}
{% block content %}
{# загружаем фильтр #}
{% load user_filters %}

<div class="row justify-content-center">
    <div class="col-md-8 p-5">
        <div class="card">
            <div class="card-header">{% if post %} Post ID {{ post.id }} {% else %}Новый пост{% endif %}</div>
            <div class="card-body">

              {% for error in form.errors %}
                  <div class="alert alert-danger" role="alert">
                      {{ error|escape }}
                  </div>
                {% endfor %}

                <form method="post" enctype="multipart/form-data" action="{% if post %}{% url 'posts:post_edit' user.username post.id %}{% else %}{% url 'posts:new_post' %}{% endif %}">

                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group row" aria-required={% if field.field.required %}"true"{% else %}"false"{% endif %}>
                                <label for="{{ field.id_for_label }}" class="col-md-4 col-form-label text-md-right">{{ field.label }}{% if field.field.required %}<span class="required">*</span>{% endif %}</label>
                                <div class="col-md-6">

                                    {# подключаем фильтр и указываем класс #}
                                    {{ field|addclass:"form-control" }}

                                    {% if field.help_text %}
                                    <small id="{{ field.id_for_label }}-help" class="form-text text-muted">{{ field.help_text|safe }}</small>
                                    {% endif %}
                                </div>
                        </div>
                    {% endfor %}

                    <div class="col-md-6 offset-md-4">
                            <button type="submit" class="btn btn-primary">
                                {% if post %} Редактировать {% else %} Опубликовать {% endif %}
                            </button>
                    </div>
                </form>
            </div> <!-- card body -->
        </div> <!-- card -->
    </div> <!-- col -->
</div> <!-- row -->

{% endblock %}

templates/paginator.html
{# Отрисовываем навигацию паджинатора только если есть и другие страницы #}
{% if page.has_other_pages %}
<nav>
  <ul class="pagination">
    {% if page.has_previous %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.previous_page_number }}">&laquo; Предыдущая</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">&laquo; Предыдущая</span>
    </li>
    {% endif %}
    {% for i in page.paginator.page_range %}
    {% if page.number == i %}
    <li class="page-item active">
      <span class="page-link">{{ i }}
        <span class="sr-only">(текущая)</span>
      </span>
    </li>
    {% else %}
    <li class="page-item">
      <a class="page-link" href="?page={{ i }}">{{ i }}</a>
    </li>
    {% endif %}
    {% endfor %}
    {% if page.has_next %}
    <li class="page-item">
      <a class="page-link" href="?page={{ page.next_page_number }}">Следующая &raquo;</a>
    </li>
    {% else %}
    <li class="page-item disabled">
      <span class="page-link">Следующая &raquo;</span>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}

templates/post.html
{% extends "base.html" %}
{% block title %}Post ID {{ post.id }}{% endblock %}
{% block header %}Post ID {{ post.id }}{% endblock %}
{% block content %}
<main role="main" class="container">
    <div class="row">
        <div class="col-md-3 mb-3 mt-1">
                {% include 'includes/user_card.html' %}
        </div>
        <div class="col-md-9">
            <!-- Пост -->
            {% include 'includes/post_card.html' %}
            {% include 'includes/comments.html' %}
     </div>
    </div>
</main>
{% endblock %}

templates/profile.html
{% extends "base.html" %}
{% block title %}Посты пользователя{% endblock %}
{% block header %}Посты пользователя{% endblock %}
{% block content %}
<main role="main" class="container">
    <div class="row">
            <div class="col-md-3 mb-3 mt-1">
                {% include 'includes/user_card.html' %}

                <li class="list-group-item">
                {% if no_author %}

                    {% if following %}
                    <a class="btn btn-lg btn-light"
                            href="{% url 'posts:profile_unfollow' author %}" role="button">
                            Отписаться
                    </a>
                    {% else %}
                    <a class="btn btn-lg btn-primary"
                            href="{% url 'posts:profile_follow' author %}" role="button">
                    Подписаться
                    </a>
                    {% endif %}
                {% else %}
                    <a class="btn btn-lg btn-primary"
                            href="" role="button">
                    Подписаться на себя нельзя!
                    </a>

                {% endif %}
                </li>

            </div>

            <div class="col-md-9">

                {% for post in page %}
                    {% include 'includes/post_card.html' %}
                {% endfor %}

                {% include "paginator.html" %}
     </div>
    </div>
</main>
{% endblock %}